### ISSUE TITLE
Meteor.subscribe does not accept parameters

### ISSUE THREAD

**Issue by imkost** [thereactivestack/meteor-react-router-ssr#11]
https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/server.jsx#L73

Original `Meteor.subscribe` can accept parameters like:

```javascript
Meteor.subscribe('categoryItems', 'category-1');
```

But server-side's `Meteor.subscribe` does not allow parameters.

**Comment by eXon** [comment]
Fixed in last release :)
