### ISSUE TITLE
Cache support

### ISSUE THREAD

**Issue by imkost** [thereactivestack/meteor-react-router-ssr#15]
It would be nice to have some sort of cache. It would save server's CPU.

I'm not sure about API for cache, but it could be something like this:

```jsx
ReactRouterSSR.Run(
  <Router>
    <Router path="/" component={LandingPage} cache={60 * 5} /> {/* cache for 5 minutes */}
    <Router path="/app" component={App} cache={0} /> {/* don't cache */}
  </Router>
);
```

**Comment by eXon** [comment]
It might be a good idea to do it if the user is not logged in, but I think it should not be the default behaviour. Meteor is especially useful for real-time apps.

Or maybe we can use the oplog to detect changes?

**Comment by imkost** [comment]
I agree, it should not be the default behaviour. Cache would be great for "static" apps: landing pages, news websites, blogs and others. Also not the whole page should be cached, but some parts (react components). So if you have blog post page, you can cache text of blog but not comments section.

Anyway, for now I don't have any problems with having no cache for ssr.

I close the issue. Maybe will reopen it in a future when I will really need this feature and/or will have some ideas about implementation.

**Comment by SachaG** [comment]
I think it'd be worth discussing this issue again. What caching strategies do people currently use? Nginx? Are there any examples of heavy traffic sites using RR-SSR in the wild?

Maybe it would make sense to have special "no SSR" or "no caching" tags (something like https://github.com/kadirahq/react-no-ssr maybe) so you could specify which parts of a page need to be cached?
