### ISSUE TITLE
Is it possible to use this with React loaded via NPM

### ISSUE THREAD

**Issue by genyded** [thereactivestack/meteor-react-router-ssr#17]
I noticed this pulls Meteor's React (react-runtime) in, so I guess it's probably not possible to use this with a non-Meteor React version loaded via NPM? 

I am trying to work around another issue with react-tap-event-plugin that needs a non-externalized React. That's why I am asking. I LOVE the ReactiveStack stuff and wanted to full steam ahead, but that issue is causing us to make some changes.

**Comment by eXon** [comment]
This is a good question. I'm not sure if it's possible but I'll look for how I can tweak this.

**Comment by eXon** [comment]
I don't see a way of doing this unless I clone this project. I don't think this is needed anymore. Meteor are updating the react package pretty quickly now.

**Comment by genyded** [comment]
Yes they just release 14.2 and with the npm package beta out - the entire landscape will be changing. I don't have the runway in my current project to wait for that to solidify though. It'll be nice not to have to hide things like webpack:webpack 'behind the curtain'. 

I think with you SSR wrapper, I can do what I need for now. Thanks again!
