### ISSUE TITLE
How do you access history in the child components?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/meteor-react-router-ssr#18]
I see that history can be added as a client option such as:

`
ReactRouterSSR.Run({
  childRoutes: [
    require('App1/client'),
    require('App2/client')
  ],
  history: new ReactRouter.history.createHistory()
});
`

How do you then reference that history later in components that are part of the child Apps? Do we just use import standard browser history and context types like a normal react app?

**Comment by eXon** [comment]
No, you don't need to create it yourself. You use the history context or the [History mixin](https://github.com/rackt/react-router/blob/master/docs/API.md#history-mixin).

Your component directly plugged on your route should receive the prop history too.

**Comment by genyded** [comment]
This seems to work using:

```javascript
export default class TestComponent extends Component {

  static contextTypes = { history: React.PropTypes.history };

  componentWillMount() {
    if (!Meteor.userId()) {
      this.context.history.pushState({}, `/test/1234`);
    }
  }

```

However there is a browser console warning:

`
Warning: Failed Context Types: Invariant Violation: AdminLayout: context type `history` is invalid; it must be a function, usually from React.PropTypes. Check the render method of 'RoutingContext'.
`

Did I miss something here or is this expected? Sorry to be a pest, but still trying to keep up with all the constant changes to Meteor, React, the router, and the reactive stack while using ES6/7. It's seems like trying to hit a moving target sometimes.

**Comment by genyded** [comment]
Never mind, figured this one out... it needs to be:


```javascript
export default class TestComponent extends Component {

  static contextTypes = { history: React.PropTypes.object.isRequired };

  componentWillMount() {
    if (!Meteor.userId()) {
      this.context.history.pushState({}, `/test/1234`);
    }
  }
...

Thanks for the quick response as always!

**Comment by eXon** [comment]
Always glad to help :)

Did you know you can also use react-router PropTypes? It will do a more accurate check on the object :)

```javascript
export default class TestComponent extends Component {

  static contextTypes = { history: ReactRouter.PropTypes.history.isRequired };

  componentWillMount() {
    if (!Meteor.userId()) {
      this.context.history.pushState({}, `/test/1234`);
    }
  }
```

**Comment by genyded** [comment]
Cool... but now I am a bit confused... React has PropTypes AND the router has PropTypes? So I guess that means 2 imports and fully qualified PropTypes in components if you happne to need both?

````javascript
import { Component, PropTypes } from 'react';
import { Link, PropTypes } from 'react-router';

static contextTypes = { 
    history: ReactRouter.PropTypes.history.isRequired,
    someOtherContextType = React.PropTypes.object.isRequired
 };

  componentWillMount() {
    if (!Meteor.userId()) {
      this.context.history.pushState({}, `/test/1234`);
    }
  }
...
````

**Comment by eXon** [comment]
You can do this!

```javascript
import { Link, PropTypes as RouterPropTypes } from 'react-router';
```

**Comment by genyded** [comment]
OK - this history crap is SUCH A PAIN... history as a prop is deprecated in react-router now... so how do we create history and how do we reference it later i the current releases???

**Comment by gunn** [comment]
Myself, I prefer:
```es6
import { browserHistory } from 'react-router'
browserHistory.push(`/test/1234`)
```

to messing around with context types.

**Comment by minfawang** [comment]
I believe @gunn's answer is the officially recommended way. I struggled on this before too, and I'm pretty sure I found the above usage was mentioned in one of the pages of the API Guide of react-router.

**Comment by genyded** [comment]
Thanks for the replies and this really isn't react router SSR's issue except to keep react router current, but  like most of the examples out there, this is actually outdated and history is always passed as a COMPONENT prop now, so it should be 'this.props.history.push(`/conferences/${permalink}/login`)' (or destructuring history and then just calling it directly). No need for the history or router PropsTypes imports in the latest react router.

Also, the old way no longer seems to work. And either way only works because History in RR is a singleton for now, so let's hope they don't change that next week ;-) Anyway thanks again for responding, it lead me to the right solution based on the current RR.
