### ISSUE TITLE
Material-UI expects the global navigator.userAgent to be defined for server-side rendering.

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#19]
Hi! I'm using [React Material UI](https://github.com/callemall/material-ui), and when deploying on production, the logs show:

``` 
Material-UI expects the global navigator.userAgent to be defined for server-side rendering. Set this property when receiving the request headers.
```

Is that something that could be fixed in the router, or is this an issue from Material UI?

**Comment by eXon** [comment]
This seems to be related to https://github.com/callemall/material-ui/issues/2316

You can probably hack a fix by mocking global.navigator for now.

**Comment by dbismut** [comment]
Indeed! I'm using your webpack meteor huge app, and at the moment, I was cloning the SSR router and adding `GLOBAL.navigator = {userAgent: headers['user-agent']};` where the Run function is defined. I guess I should be able to do the same in the `preRender` hook...

**Comment by eXon** [comment]
I'm closing this because I believe it is more of a material-ui bug. I don't think we need to fix something here.
