### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by rclai** [thereactivestack/meteor-react-router-ssr#2]
https://github.com/thereactivestack/meteor-react-router-ssr/blob/6e1c4a96ad5a888490e51a0c0bab8c61c00f911a/lib/server.jsx#L29-L31

This package is pretty cool!

**Comment by eXon** [comment]
Damnit you're right! Thank you for pointing this out.

If you need any help or have others comments, let me know this is brand new :)

**Comment by rclai** [comment]
Haha, no problem. Thanks.
