### ISSUE TITLE
How to specify options using ReactRouterSSR.Run

### ISSUE THREAD

**Issue by genyded** [thereactivestack/meteor-react-router-ssr#20]
I see a place for client and server options using the ReactRouterSSR.Run command, but no example. If I had the following route file normally, how would this look as a ReactRouterSSR.Run command?

    import configureStore from 'NewApp/client/store';
    import createHistory from 'history/lib/createBrowserHistory';

    const history = createHistory();
    const store = configureStore(history);

    ....

      <Provider store={store}>
          <Router history={history}>
            {routes}
          </Router>
       </Provider>

    ....

**Comment by genyded** [comment]
In order to support the Redux flavor of Flux... the Router element has to be wrapped in a Provider and passed parameters as indicated [here] (https://github.com/rackt/react-redux/blob/master/docs/api.md#react-router-10) . Since ReactRouterSSR 'shields' this - is there a way to add this without forking and tweaking the package?

**Comment by eXon** [comment]
I added the wrapper option (on clientOptions and serverOptions so they can be different). 

If you use Redux, you probably want to use the redux-router too. It's the same as react-router, but the state is saved inside redux.

I personally think redux has little to no value inside Meteor but hey, if it serves you well why not :)

**Comment by genyded** [comment]
Thanks... the primary driver for redux is managing state across a mass of React components.
