### ISSUE TITLE
how to set <head/>

### ISSUE THREAD

**Issue by yinzSE** [thereactivestack/meteor-react-router-ssr#22]
hi, I have a question.

how to reactive set `<head/> <title/>` without `html` template

**Comment by eXon** [comment]
You can put React components inside <head /> for sure. What are you trying to do?

**Comment by yinzSE** [comment]
emm,
it means `ReactRouterSSR.Run(AppRoutes)` just append components into `<body />`.

The other tag in `<head />` should use `Spacebars` just like `<title />`, right?

**Comment by eXon** [comment]
You can use either spacebars or static-html to append stuff to `<head />`. SSR is only touching the body.
