### ISSUE TITLE
"Match error: Failed Match.OneOf or Match.Optional validation"

### ISSUE THREAD

**Issue by john-osullivan** [thereactivestack/meteor-react-router-ssr#23]
Hello again, @eXon !  Sorry to be bothering you once more, but I'm running into an issue and I think it's because of updating the meteor-react-router-ssr package.  Some code which was previously working fine under version 0.2.13 is now broken after I updated to version 0.3.5, and I was hoping you could cast some light onto why it might be happening.

![image](https://cloud.githubusercontent.com/assets/3820981/11904070/aba4b4b0-a58b-11e5-86b5-285d64862419.png)

My component is subscribing to a composite publication (made via reywood:publish-composite), sending one argument object which contains the ID of a document whose data should be returned by the publication.  Based on my manual inspection of the database and the arguments being sent, I know the correct document exists and is being requested with the correct ID.  I thought the bug might be in publish-composite, but that package wasn't updated.

The route of the component is `/app/groups/:groupName`, and the page tries to extract an optional query parameter from `this.props.params`.  This bug is happening when I try to access the page without the additional query param.  Any ideas on why this might be happening?

Thank you!

**Comment by eXon** [comment]
Have you tried updating to 1.0.2_2? 

You might need to remove and re-add the react-router-ssr package but there is no breaking changes. Now it follow the react-router version.

**Comment by john-osullivan** [comment]
I just upgraded again and the bug is still there, but this package is no longer included in the stack trace.  Looks like it's something going wrong over at reywood:publish-composite!  As always, thanks for the prompt help -- I'll close this issue right up.
