### ISSUE TITLE
Default route

### ISSUE THREAD

**Issue by Valbrand** [thereactivestack/meteor-react-router-ssr#3]
How should one put his routes in order to have the same effect as the v0.13's `DefaultRoute`? I assumed the example on the README (making an inner `Route` object with the `path` prop set as `/`) covered that, but it doesn't: all that's rendered is the outer route handler.

**Comment by eXon** [comment]
Their is no more DefaultRoute. The easiest way to do it is to check if this.props.children is undefined and set the component you want to use as default route.

**Comment by eXon** [comment]
Example:

```javascript
render() {
   const children = (this.props.children) ? this.props.children : <MyDefaultComponent />;
  return children;
}
```

**Comment by Valbrand** [comment]
Understood. Problem solved!
