### ISSUE TITLE
How to create Auth Flow ?

### ISSUE THREAD

**Issue by C0r3y8** [thereactivestack/meteor-react-router-ssr#30]
Hi,

I'm a beginner with React and i try to dev auth flow for my meteor app.

__First try__

I try the [solution](https://github.com/meteor/react-packages/issues/102) of @eXon but i get this error:
```bash
Warning: Failed Context Types: Required context `router` was not specified in `Auth`. Check the render method of `RoutingContext`.
```

`routes.jsx`
```javascript
const { IndexRoute, Route } = ReactRouter;

Meteor.startup(function () {
  AppRoutes = (
    <Route component={Layout}
        path='/'
    >
      <Route component={Auth}>
        <IndexRoute component={Login} />
      </Route>
      <Route component={Restricted}>
        <Route component={DashboardLayout}
            path='dashboard'
        >
          <IndexRoute component={DashboardHome} />
        </Route>
      </Route>
    </Route>
  );

  ReactRouterSSR.Run(AppRoutes);
});
```

`auth.jsx`
```javascript
Auth = React.createClass({
  displayName: 'Auth',

  propTypes: {
    children: React.PropTypes.node.isRequired
  },

  contextTypes: {
    router: React.PropTypes.object.isRequired
  },

  componentDidMount() {
    if (Meteor.userId()) {
      this.context.router.transitionTo('/dashboard');
    }
  },

  render() {
    if (Meteor.userId()) {
      return null;
    }

    return this.props.children;
  }
});
```

__Next try__

I follow the [react router auth flow example](https://github.com/rackt/react-router/blob/master/examples/auth-flow) but get this:
`Exception in callback of async function: TypeError: Cannot read property 'query' of undefined`

`routes.jsx` looks like same that before just add onEnter property. (`routes.jsx` is known by server and client)

__Other__

I try other solutions like separate server and client routes but still getting `Exception in callback of async function: TypeError: Cannot read property 'query' of undefined`.

If anyone can help me pls ?

**Comment by dbismut** [comment]
Hey - just to let you know, I'm using redux but the auth flow I use is similar to [this one](https://github.com/joshgeller/react-redux-jwt-auth-example/blob/master/src/components/AuthenticatedComponent.js). It doesn't use `onEnter` hooks.

**Comment by C0r3y8** [comment]
Hello @dbismut , thanks for your answer :), it works fine !
