### ISSUE TITLE
[Redux] Can store be passed as a parameter to routes?

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#35]
I guess this one is for you @yched :)

It's not urgent so don't bother if you don't have time at the moment, you already helped me a hell lot.

I was curious if the `store` could be passed as a parameter to the routes, similarly to what seems to be the current usage to handle auth flow (see react redux universal app [routes](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/routes.js) and [routes creation](https://github.com/erikras/react-redux-universal-hot-example/blob/c22755e52565f0bfc829d88d31cb92b9749b8145/src/client.js#L43)) or reducers code splitting ([latest pseudo code from @gaeron](https://gist.github.com/gaearon/0a2213881b5d53973514)).

Thanks once again!!

**Comment by yched** [comment]
hm tricky...

I didn't look at that in detail, but I don't think there are huge obstacles per se to having ReactRouterSSR.Run() create the store before doing the routing (that's the case on the client side, but on the server side routing is done first atm).

The main obstacle seems to be the current shape of the ReactRouterSSR.Run(routes, options) API, which de-facto mandates that you define and pass your routes upfront, before can call your optionqs.createReduxStore callback :-/

**Comment by dbismut** [comment]
Ok thanks for the feedback, I'll live with it for now.

**Comment by dbismut** [comment]
Btw, `redux-simple-router` is now `react-router-redux` and does not have `syncReduxAndRouter` as from [2.0.2](https://github.com/rackt/react-router-redux/blob/master/CHANGELOG.md#202).

> syncReduxAndRouter is gone. Instead, call syncHistory with just the history object, which returns a middleware that you need to apply. (#141)

That means that the ReadMe is outdated, and to show the example with `react-router-redux` would mean you would have to deal with introducing middlewares, etc. I think you might want just to remove the line related

**Comment by yched** [comment]
Oh, I heard that the redux-simple-router -> react-router-redux rename was on the way, but wasn't aware it did happen, thanks for the heads up !

 I'll check it out and submit a PR to update the code samples (good move on their side for the middleware, I always found syncReduxAndRouter() a bit weird :-)

**Comment by eXon** [comment]
Do any action is needed here? We should close this if not or let me know because it is not clear.

**Comment by dbismut** [comment]
Yes, an action would be needed. At the moment, routes are created independently from the store resulting from `createReduxStore`. Ideally, this would mean that you would pass routes as the result of a function taking the redux store as its main argument, like let's say:

```javascript
ReactRouterSSR.Run({
    component: CommonApp,
    childRoutes: (store) => createRoutesFromStore(store)
}, clientOptions, serverOptions);
```

Having access to the store from the routes would allow easier auth system.

I understand redux is not a critical aspect of this project, so it's fine to leave this aside until someone comes up with a solution, but I don't think we should close the issue unless the answer is a definitive no, we just can't do it.

**Comment by eXon** [comment]
Unless you have a hook we need to add that is missing we'll close this for now.
