### ISSUE TITLE
Out of sync with react router, history, etc

### ISSUE THREAD

**Issue by genyded** [thereactivestack/meteor-react-router-ssr#36]
This is hard coded to react router 1.0.x (which means History and others must also be 1.0.x). These are all at 2.0.0-rcX now and all the docs and examples for them are updated to reflect this. It makes it really hard for anyone new to figure all that out. Also many of the API's depend on integrating with other things like Redux, so again having them outdated can cause major integration issues.

Is there any way we can get these updated without having a modified local copy of the package?

**Comment by eXon** [comment]
Not at the moment. I'm looking for a way to let you get react-router from NPM by yourself though. I'll upgrade this package when the 2.0 will be released.
