### ISSUE TITLE
React Helmet doesn't work on Server side

### ISSUE THREAD

**Issue by vuongngo** [thereactivestack/meteor-react-router-ssr#39]
Hi @eXon , I just noticed that Helmet is not added to <head> on server side because it need .toString() method in server. It would be great if you can fix it :) . Cheers

**Comment by yched** [comment]
Weird, Helmet seems to work fine on the server-side on my sample app :

Somewhere in my components tree : (on my route entry component, in this case)
`<Helmet title="My title" />`

Then :
`curl http://localhost:3000` does contain `<head><title data-react-helmet="true">Meteor Leaderboard - List list1</title>...`

I'm using react-helmet 2.2.0, didn't check with the latest version though

**Comment by vuongngo** [comment]
hm. I'm not sure why. 2.2.0 does not work on my project on serverside rendering though :( . Here's my working [project ](https://github.com/DitchCrab/ReactiveForum/commits/master). It would be great if you can help me out. Thanks

**Comment by eXon** [comment]
I'll check this when I have some time. They might have changed something in their API.

**Comment by eXon** [comment]
It seems to work find with the last version. Let me know if you're still having troubles and I'll try to dig deeper.
