### ISSUE TITLE
Migration to react-router 2.0

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#42]
Hey @eXon, noticed you moved to react-router 2.0, cool :+1: 

There's just this one line where the history is created for the redux store, I believe it was a PR from @yched: https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/server.jsx#L203

You might want to change it to:

```javascript
const history = ReactRouter.createMemoryHistory();
```

Therefore you should not need the history dependency in `meteor-react-router` (`ReactRouter.history = require(history)`, as per [this change](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#history-singletons-provided) from react-router 2.0.

> We now include singleton history instances for you to use in the router. They are hashHistory (hash-based URLs) and browserHistory (HTML5 pushState "pretty" URLs). They include any needed history wrappers (such as useQueries) so you don't have to write as much boilerplate as before.

> Another big change because of this is history is now a normal dependency. You no longer have to install and maintain history separately. Batteries included!

Cheers!

**Comment by eXon** [comment]
Thanks for the tip, I'll change it.

I'll still have to keep it because I want to keep it retro-compatible.
