### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by gunn** [thereactivestack/meteor-react-router-ssr#43]
ReactRouterSSR has a dependency on meteorhacks:inject-data for syncing redux data.

Despite not using redux, inject-data and it's dependencies jquery and underscore are included with my client-side production build.

Is there a way we can eliminate these?

**Comment by yched** [comment]
Even without the redux support, react-router-ssr uses fastrender, which itself depends on inject-data.

That's why the redux support was built using inject-data - because the dependency was already there as a second-level dependency

**Comment by gunn** [comment]
@yched Ah. I suppose that makes it a non-issue. Good news on the jquery and underscore dependencies anyway: meteorhacks/inject-data#6
