### ISSUE TITLE
webpack / meteor 1.3 support

### ISSUE THREAD

**Issue by tonyxiao** [thereactivestack/meteor-react-router-ssr#45]
When using webpack or meteor 1.3 we are moving away from `react-runtime` to directly using npm module `react` or `react-helmet`. The code as is is not compatible with that pattern and end up requiring multiple copies of react for example

**Comment by eXon** [comment]
I agree this library needs to be migrated to 1.3 and use React from NPM. I'll probably make a separate package until Meteor 1.3 is out of beta.

**Comment by cheersjosh** [comment]
Any update on this @eXon? I'd eager to add SSR support to my boilerplate [here](https://github.com/cheersjosh/corona)

**Comment by minfawang** [comment]
Just a heads up. Meteor 1.3 is out of beta now :heart_eyes:

**Comment by MadeInMoon** [comment]
It would make my days so brighter :)

**Comment by eXon** [comment]
Just noticed it :fireworks: 

I'll release something for 1.3 soon.

**Comment by csillag** [comment]
> I'll release something for 1.3 soon.

We are looking forward to that release!

**Comment by eXon** [comment]
Version 3.0 is 1.3 compatible and use everything from NPM :)
