### ISSUE TITLE
Any plans to provide an upgrade/migration path?

### ISSUE THREAD

**Issue by genyded** [thereactivestack/meteor-react-router-ssr#47]
Hi Benoit,

I see a LOT of changes:

- No more webpack.packages,json

- startups are in lib now instead of entry (at least for ssr - looks like other are in src now)

- No more HUGEAPP??  ;-(

So. are there plans to provide an upgrade or migration plan for stuff written with the old version(s)? Or are you letting folks figure that out for themselves and start over?

**Comment by eXon** [comment]
You can [read the changelog](https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/CHANGELOG.md), it includes the migration path.

**Comment by eXon** [comment]
Your project should migrate a lot of stuff automatically and you can still use your webpack.config.js files if you don't want to use Meteor packages instead for now.

**Comment by eXon** [comment]
You can read the [migration guide in the changelog](https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/CHANGELOG.md). It contains everything you need.

It should be painless, you can even keep your webpack.config.js until you have time to migrate to Meteor packages afterward.
