### ISSUE TITLE
Subscription in Route onEnter

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#48]
Hey @exon, I'm currently trying to implement an auth mechanism based on react-router onEnter hook.

I need to subscribe to a collection in that hook, and therefore the subscription server-side happens before `generateSSRData()` where you temporarily reassign `Meteor.subscribe` to `SSRSubscription`. 

I was wondering if it would make sense or even if it was useful to move `Meteor.subscribe = SSRSubscribe(context)` before `ReactRouter.match`?

Thanks!

**Comment by eXon** [comment]
I'll take a quick look at it and let you know. Shouldn't be a problem.

**Comment by eXon** [comment]
Sorry I had no time to look at this. I'll try to review this one in the next few days.

**Comment by eXon** [comment]
Should be fixed on master :)
