### ISSUE TITLE
React 15

### ISSUE THREAD

**Issue by gunn** [thereactivestack/meteor-react-router-ssr#50]
Including this when using react 15 breaks things:
```
WARNING: npm peer requirements not installed:
 - react@15.0.1 installed, react@0.14.x needed
 - react-dom@15.0.1 installed, react-dom@0.14.x needed
 - react-addons-transition-group@0.14.x not installed.

Error: Can't find npm module 'react-addons-transition-group'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
```
There's a dependency on `react-runtime@0.14.0` -  https://github.com/thereactivestack/meteor-react-router-ssr/blob/9b28eb8c769139/package.js#L19. I don't know if it's the only problem because there are a lot of secondary dependencies.

**Comment by eXon** [comment]
Done! Just get the 3.0 :)
