### ISSUE TITLE
What if SSR rendering fails on server?

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#53]
Hey @eXon, I may have found a critical issue, although I'm far from being sure. I had a close look at the method `generateSSRData` on the [server, L173](https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/server.jsx#L173).

It seems like you're setting `Mongo.Collection._isSSR = true;` and setting it back to `false` within the `try` statement, so if anything wrong happens with the rendering in between, `Mongo.Collection._isSSR` will never revert to `false`.

It seems to me like this could be a problem, although I'm not sure. To be honest, I'm not exactly sure what happens on the server on each client request: is each request supposed to be running in its own environment? If you could explain this quickly that would be a huge help. Thanks a million.

EDIT: also, can you explain why [this line](https://github.com/thereactivestack/meteor-react-router-ssr/blob/master/lib/server.jsx#L26) is needed?

```javascript
const url = Npm.require('url');
const Fiber = Npm.require('fibers');
```

**Comment by dbismut** [comment]
Ok well, I looked at the code of FlowRouter SSR and although I don't understand everything yet, the mechanism they're using is close to what you're doing.

However, it looks like your setting `Mongo.Collection._isSSR` globally while FlowRouter seems to be using an EnvironmentVariable (such as SSRContext).

What worries me - but I'm probably wrong, is that _isSSR seems to be set to true globally and not just for the current fiber / client request? That would mean that if a request from client B is made while the server is rendering for client A, something bad could happen?

Again sorry if this doesn't make sense.

**Comment by dbismut** [comment]
@eXon: here is a working version (server-side code only) that replicates some of FlowRouter's mechanisms with use of `Meteor.EnvironmentVariable`.

https://gist.github.com/dbismut/7af512a597fdb897f4958178f0856e77

It would be super cool if you could have a look and let me know what you think, in particular the use of the `context` variable.

PS: I'm using a heavily patched version of ReactRouterSSR (it's not a package anymore in my app) and since it uses a redux store, some of the mechanisms are a bit tweaked. But it's the very same logic and shouldn't differ too much from your code.

**Comment by eXon** [comment]
Is it still a problem?

**Comment by dbismut** [comment]
Hi @eXon, yes it's still a problem, and I think a pretty major one.

To illustrate it, I've created a repo here:
https://github.com/dbismut/kickstart-meteor-react-router-ssrbug

It's a clone of your own kickstart-meteor-react-router project, with the following changes:

- **TodoApp.jsx**: Line 8 is commented because of an [issue](https://github.com/thereactivestack/kickstart-meteor-react-router/issues/78) with the css loader in your webpack config. I'm not sure what happens there but it's unrelated.
- **TodoHeader.jsx**: In the `render` function, I'm throwing a `Meteor.Error` to simulate a server-side rendering error.
- **server.js**: Finally, I'm adding a user to the `Meteor.users` collection just to illustrate my point.

Here are the steps to reproduce the bug:

1. Launch the app in production `meteor run --production` to enable SSR
2. Launch the meteor shell in a separate terminal window
2. **Don't launch your browser window just yet!!**
3. In the shell, type `Meteor.users.findOne()`. You should see the testuser I've created
4. Now open `localhost:3000` in a browser window.
5. In the first terminal window from which you launched meteor, you should see the result of the fake SSR error I've introduced.
6. Now in the meteor shell, type `Meteor.users.findOne()`. Nothing should show.

That means that if a SSR error is encountered in one of the client requests, then `Meteor.users.findOne()` will return nothing **globally** for the server. And this is really bad: as much as the server can indeed bug when rendering, the collateral damages should only affect the client session that introduced the error, not the bring down whole server environment.

I've explained above the general code to fix this, if you want to take a look.

**Comment by eXon** [comment]
It looks like a major bug I agree. I'll take a look.

**Comment by eXon** [comment]
This has been bothering me for a LONG time. Seriously.... THANKS a lot for your code I literally took it and ran with it. I've removed everything non react-router realted though but you should have all the required hook to be able to use it with Redux.

Let me know if it work great for you! :)

**Comment by dbismut** [comment]
You don't have to thank me. I stole the code from FlowRouter SSR. Glad I could help though ;)
