### ISSUE TITLE
How to make CSS load in Server-Side Rendering?

### ISSUE THREAD

**Issue by ahmadsafar** [thereactivestack/meteor-react-router-ssr#60]
i see in lib/server.jsx file it have 'css' text. so i think that for supporting CCS Load in SSR. But i dont know how to do it?

**Comment by eXon** [comment]
Hust use regular .css files and server-rendering will be fine.

If you're using Webpack you can import your .import.css files where you need them and they are going to be bundled automatically.

**Comment by ahmadsafar** [comment]
got it, thanks
