### ISSUE TITLE
Getting error on ReactRouterSSR.Run

### ISSUE THREAD

**Issue by mrlarssen** [thereactivestack/meteor-react-router-ssr#61]
Whenever I run ReactRouterSSR.Run(myRoutes) I get the following error:

main.jsx:7Uncaught TypeError: _reactrouterReactRouterSsr2.default.Run is not a function
`
import ReactRouterSSR from 'meteor/reactrouter:react-router-ssr';

myRoutes = (
    < Route >
    ......
    < / Route >
)

ReactRouterSSR.Run(myRoutes)`

Any ideas?

Edit: On the server im getting: Object [object Object] has no method 'Run'

I have also imported react-router.

**Comment by leocavalcante** [comment]
Got the same. It seams that RRSSR isn't the default export anymore. You should: `import { ReactRouterSSR } from 'meteor/reactrouter:react-router-ssr';`

**Comment by SachaG** [comment]
@leocavalcante thanks! I couldn't figure this out…
