### ISSUE TITLE
Server renders without data

### ISSUE THREAD

**Issue by leocavalcante** [thereactivestack/meteor-react-router-ssr#64]
```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) l data-reactid="5"></ul></div>
 (server) l data-reactid="5"><li data-reactid="6">
```

This is because I'm using [guide's way to fetch data into React](http://guide.meteor.com/react.html#data)?

**Comment by eXon** [comment]
Do you mind pasting here your data fetching code?

**Comment by leocavalcante** [comment]
Well, sorry, I haven't figured out why, but this problem I had at my work machine and now, at home, I tried to re-do an example to show the "issue", but it works :laughing: 
Anyway, here is it: https://github.com/leocavalcante/meteor-react-router-ssr-example
