### ISSUE TITLE
Is code splitting possible?

### ISSUE THREAD

**Issue by jschlieber** [thereactivestack/meteor-react-router-ssr#75]
As we know ([e.g. from here](https://medium.com/@SamCorcos/meteor-webpack-react-router-a-basic-template-with-code-splitting-ac2f95d151e2#.qtq7rokc6)) code splitting with Meteor and Webpack is possible. Is it possible with **meteor-react-router-ssr** as well?

**Comment by eXon** [comment]
Yes you can. All you need to do is make sure there is code splitting on the client only (using Meteor.isClient).
