### ISSUE TITLE
Disable SSR on certain routes

### ISSUE THREAD

**Issue by clayne11** [thereactivestack/meteor-react-router-ssr#78]
I'd like to be able to enable SSR on specific routes. Right now it's either blanket on or off. It would be very helpful to be able to add it only to pages that I know will work and not to ones that won't.

This way I can gracefully add in SSR to pages that support it.

**Comment by themeteorchef** [comment]
This would be super handy :)

**Comment by eXon** [comment]
Your page has to be an entire SPA. You can stop the server-rendering at any level by using componentDidMount and a state. Their is no plan to support this because the SPA handles the routing and it would be weird.

**Comment by themeteorchef** [comment]
Could you share an example of stopping the render in componentDidMount?

**Comment by CaptainChemist** [comment]
I would really appreciate an example of disabling SSR on certain routes using componentDidMount as well.
