### ISSUE TITLE
Unable to get user on server-side

### ISSUE THREAD

**Issue by imkost** [thereactivestack/meteor-react-router-ssr#8]
```javascript
getMeteorData() {
  // Works right, prints id of currently logged in user on both: client and server
  console.log(Meteor.userId());

  return {
    user: Meteor.users.findOne(Meteor.userId()) // Does not work on server
  }
}
```

I see this error:
```
W20151017-00:08:36.253(3)? (STDERR) error while server-rendering TypeError: Object [object global] has no method '_getFindSelector'
W20151017-00:08:36.254(3)? (STDERR)     at _.extend.find (packages/mongo/collection.js:279:1)
W20151017-00:08:36.254(3)? (STDERR)     at [object Object].Mongo.Collection.find (packages/reactrouter_react-router-ssr/lib/server.jsx.js:219:1)
W20151017-00:08:36.254(3)? (STDERR)     at Page.getMeteorData (eval at <anonymous> (server.js:71:1), <anonymous>:164:32)
W20151017-00:08:36.254(3)? (STDERR)     at MeteorDataManager.calculateData (meteor-data-mixin.jsx:62:24)
W20151017-00:08:36.254(3)? (STDERR)     at Page.ReactMeteorData.componentWillMount (meteor-data-mixin.jsx:5:45)
W20151017-00:08:36.255(3)? (STDERR)     at Page.eval (eval at <anonymous> (server.js:221:1), <anonymous>:137:26)
W20151017-00:08:36.255(3)? (STDERR)     at Page.eval (eval at <anonymous> (server.js:221:1), <anonymous>:55:34)
W20151017-00:08:36.255(3)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (packages/react-runtime-dev/react.browserify.js:6804:1)
W20151017-00:08:36.255(3)? (STDERR)     at [object Object].wrapper [as mountComponent] (packages/react-runtime-dev/react.browserify.js:13941:1)
W20151017-00:08:36.255(3)? (STDERR)     at Object.ReactReconciler.mountComponent (packages/react-runtime-dev/react.browserify.js:14758:1)
I20151017-00:08:38.980(3)? Exception from sub meteor.loginServiceConfiguration id E6kosSDqEvM6mdHSu TypeError: Object [object global] has no method '_getFindSelector'
```

I also tried `Meteor.user()` and `Meteor.users.find(Meteor.userId())`. Same error

**Comment by imkost** [comment]
There is a walkaround (this walkaround is presented in README, so I suppose it's a known issue): use some other collection, Profile, for example, which is connected with `Meteor.users` by some key

**Comment by eXon** [comment]
This is not supposed to crash. However, you forgot your subscription (unless you have autopublish). Is it working with it?

I guess we should add an exception to allow anybody to access his own user object. Is it part of the meteor spec?

**Comment by eXon** [comment]
In my project I have this:

```javascript
Meteor.publish('profile', function() {
  return Meteor.users.find(this.userId);
});
```

Does it work for you?

Do you normally have access to your own user object completely?

**Comment by imkost** [comment]
Cool! Yes, this does work. I didn't have autopublish.

I think it would be useful to have such an example in README. It was not obvious for me, that I have to subscribe for my own user.

**Comment by eXon** [comment]
After doing some digging, it has nothing to do with the publish. There is a type check on mongo for the options in find and it seems to be failing. I don't know why. I've just disabled the check and the user seems to be available.

**Comment by skosch** [comment]
I'm suffering from the same problem. I don't think the workaround should be required. I tried typing `Meteor.user()` in the browser console of a plain Meteor app and got – paraphrasing, of course:
```
▶ Meteor.user()
  Object {_id: "o7v4Rw9wtoZwo2ixF", username: "sebastian", profile: Object}
    _id: "o7v4Rw9wtoZwo2ixF"
    profile: Object
        shoeSize: "10"
        role: "admin"
    __proto__: Object
    username: "sebastian"
```
So I think it's safe to say that the user object should just be provided. (Also, I'm relying on it throughout my project, and adding a pseudo-subscription would be quite annoying :-)

**Comment by skosch** [comment]
P.S. calling `Meteor.users.findOne(Meteor.userId())` returns the same thing. while `Meteor.users.find().fetch()` returns an array with just your own object. 

I've tried using
```
    if (!Mongo.Collection._isSSR ||
          this._name === "users" ||
          this._name === "meteor_autoupdate_clientVersions" ||
          this._name === "meteor_accounts_loginServiceConfiguration") {
      return originalFind.apply(this, args);
    }
```
and that works. I wonder what a clean solution would look like?

Also, I pulled my hair out for a while over a cryptic error message that had to do with my using `Meteor.user` within a `componentWillMount` function, which wasn't a problem before SSR. Some of these gotchas are really subtle!

**Comment by skosch** [comment]
Unfortunately, I'm still getting a whole bunch of errors due to the leak-protection publication checks. I've now commented out all of

```javascript
// Make sure to return nothing if no publish has been called
/*if (!Mongo.Collection._publishSelectorsSSR[this._name] || !Mongo.Collection._publishSelectorsSSR[this._name].length) {
  return originalFind(undefined);
}

if (args.length) {
  args[0] = { $and: [args[0], { $or: Mongo.Collection._publishSelectorsSSR[this._name] }] };
} else {
  args.push({ $or: Mongo.Collection._publishSelectorsSSR[this._name] });
}*/
```
... and *finally* it runs without eternally printing stderr messages on the server side.

Maybe it's not finding my publishes somehow? I realize the checks are there for a reason, but I'm stuck trying to debug this ...

**Comment by eXon** [comment]
If you have any error please create a bug issue with it or I can't help you.
