### ISSUE TITLE
How can you test if this is actually working?

### ISSUE THREAD

**Issue by kdanninger** [thereactivestack/meteor-react-router-ssr#80]
When I `curl` even with `?__escaped_fragment__=` how do you know that this is actually crawlable by a bot or headless browser?

**Comment by kdanninger** [comment]
Lol, I'm just a derpy pants. Got it.

![](https://media.giphy.com/media/27EhcDHnlkw1O/giphy.gif)

**Comment by josh91hickman** [comment]
@karldanninger having a hard time with this as well, how'd you figure out if it was working?

**Comment by copleykj** [comment]
using `curl` or viewing the page source in the browser should yield the html that is generated by React for your app.
